apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
spec:
  type: LoadBalancer
  selector:
    app: sagile-web
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  
